package llm

import (
	"context"
)

// Role represents the role of a message participant in a chat completion.
type Role string

const (
	// RoleSystem denotes instructions and context guiding the assistant's behavior.
	RoleSystem Role = "system"

	// RoleUser denotes user input and goals.
	RoleUser Role = "user"

	// RoleAssistant denotes responses, thoughts, or tool calls generated by the model.
	RoleAssistant Role = "assistant"

	// RoleTool denotes the output returned from executing a tool.
	RoleTool Role = "tool"
)

// FunctionCall holds the function name and JSON arguments.
type FunctionCall struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// ToolCall represents a request from the LLM to execute a specific tool with arguments.
type ToolCall struct {
	ID       string       `json:"id"`
	Type     string       `json:"type"`     // "function"
	Function FunctionCall `json:"function"`
}


// Message represents a single turn in a multi-turn conversation.
type Message struct {
	Role       Role       `json:"role"`
	Content    string     `json:"content,omitempty"`
	ToolCalls  []ToolCall `json:"tool_calls,omitempty"`
	ToolCallID string     `json:"tool_call_id,omitempty"`
}



// FunctionDef holds the name, description, and schema for a tool.
type FunctionDef struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Parameters  interface{} `json:"parameters"`
}

type ToolDefinition struct {
	Type     string      `json:"type"` // "function"
	Function FunctionDef `json:"function"`
}


// ChatRequest encapsulates the payload sent to an LLM provider.
type ChatRequest struct {
	Model   string    `json:"model"`
	Message []Message `json:"messages"`
	Tools   []ToolDefinition `json:"tools,omitempty"`
}

// ChatResponse encapsulates the parsed answer returned from an LLM provider.
type ChatResponse struct {
	Content   string     `json:"content"`
	ToolCalls []ToolCall `json:"tool_calls,omitempty"`
}


// Provider is the common interface implemented by all LLM client adapters (OpenAI, DeepSeek, Claude, Gemini, etc.).
type Provider interface {
	// Name returns the provider identifier (e.g. "openai", "anthropic", "gemini").
	Name() string

	// Generate sends a chat completion request to the LLM and returns the generated response.
	Generate(ctx context.Context, req *ChatRequest) (*ChatResponse, error)
}
